# Generated by Django 4.2.7 on 2025-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
    ]
