# Generated by Django 4.2.7 on 2025-09-24 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=100)),
                ('location_area', models.CharField(blank=True, max_length=200)),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand_multiplier', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('competition_factor', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('urgency_factor', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('market_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('demand_forecast', 'Demand Forecasting'), ('price_optimization', 'Price Optimization'), ('provider_recommendation', 'Provider Recommendation'), ('sentiment_analysis', 'Sentiment Analysis')], max_length=30)),
                ('input_data', models.JSONField(help_text='Input features used for prediction')),
                ('prediction_result', models.JSONField(help_text='Model prediction output')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='Model confidence (0-1)', max_digits=5, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=100)),
                ('location_area', models.CharField(blank=True, max_length=200)),
                ('forecast_date', models.DateField()),
                ('predicted_demand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_interval', models.JSONField(default=dict)),
                ('seasonal_factor', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('trend_factor', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('external_factors', models.JSONField(default=dict)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('service_category', 'location_area', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, max_length=100)),
                ('compatibility_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('distance_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('rating_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('price_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('availability_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('factors_used', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_scores', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendation_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('customer', 'provider', 'service_category')},
            },
        ),
    ]
