# Generated by Django 4.2.7 on 2025-10-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "examples",
                    models.JSONField(
                        default=list, help_text="Example phrases for this intent"
                    ),
                ),
                (
                    "response_template",
                    models.TextField(
                        blank=True, help_text="Template for responses to this intent"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="chatbotknowledge",
            name="confidence_score",
            field=models.FloatField(
                default=1.0, help_text="Confidence score for this knowledge entry"
            ),
        ),
        migrations.AddField(
            model_name="chatbotknowledge",
            name="entities",
            field=models.JSONField(
                blank=True, default=dict, help_text="Extracted entities and their types"
            ),
        ),
        migrations.AddField(
            model_name="chatbotknowledge",
            name="intent",
            field=models.CharField(
                blank=True,
                help_text="Intent classification for this knowledge entry",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chatbotknowledge",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ChatbotEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("service", "Service Type"),
                            ("location", "Location"),
                            ("time", "Time/Date"),
                            ("price", "Price"),
                            ("person", "Person Name"),
                            ("contact", "Contact Info"),
                            ("custom", "Custom Entity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "synonyms",
                    models.JSONField(
                        default=list, help_text="Synonyms for this entity"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["entity_type", "name"],
                "unique_together": {("name", "entity_type")},
            },
        ),
        migrations.CreateModel(
            name="ChatbotAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent_detected", models.CharField(blank=True, max_length=100)),
                ("entities_extracted", models.JSONField(default=dict)),
                (
                    "response_time",
                    models.FloatField(help_text="Response time in seconds"),
                ),
                (
                    "user_satisfaction",
                    models.IntegerField(
                        blank=True,
                        help_text="User satisfaction rating (1-5)",
                        null=True,
                    ),
                ),
                (
                    "conversation_length",
                    models.PositiveIntegerField(
                        help_text="Number of messages in conversation"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Whether the user's query was resolved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
